### PR TITLE
My receipts page UI

### LINKED ISSUE #19: My Receipts Page UI
My Receipts Page UI from Figma Designs

Image

### PR DESCRIPTION
**Pull request by SamuelLiSiyuan**
A prototype of the receipts page UI

image

### CODE REVIEW

**Comment by LideLinusZhang** [comment]
Your branch should be based on `main` instead of your previous personal branch.

**Review by LideLinusZhang — CHANGES_REQUESTED** [review]
Your branch should be based on `main` instead of your previous personal branch and free of conflicts.

**Review by sophiezychan — CHANGES_REQUESTED** [review]
Can you please include a screenshot of the UI in the description?

**Review by NandiniMeh — COMMENTED** [review]
Changes needed as per new figma designed (added in the PR description):

- Filter for 'Payment Type' (using the payment type enum as dropdown values)
- Filter for 'Card Used' (using the names of the saved cards of the user)
- Card Used and Purchase Type shown as well for each receipt (when we record a receipt now, the user has to indicate which card they used and what was the purchase type (grocery, gas, etc) so show that as well)
- Record a Receipt Button
- The my receipts page is now in the nav bar, and not from the my cards page.

**Comment by SamuelLiSiyuan** [comment]
I will change it to a new branch and also update changes for new designs.  I will close this PR by then.

**Pull request closed without merging**
